spring:
  datasource:
    url: jdbc:mysql://host.minikube.internal:3306/customer_db
    username: customerdbuser
    password: customer@123
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
  jpa:
    hibernate:
      ddl-auto: update
